### ISSUE TITLE
Use set-immediate-shim

### ISSUE THREAD

**Issue by floatdrop** [floatdrop/pinkie#1]
Should `pinkie` use [`set-immediate-shim`](https://www.npmjs.com/set-immediate-shim) instead of [this lines](https://github.com/floatdrop/pinkie/blob/master/index.js#L9)?

//cc @sindresorhus

**Comment by sindresorhus** [comment]
Nah, it's nice that `pinkie` is dependency-less as I'm going to use it in a lot of modules.
