### ISSUE TITLE
Not found on NPM

### ISSUE THREAD

**Issue by Eldelshell** [floatdrop/pinkie#16]
It seems this package has been removed from the NPM registry somehow. It shows on searches but fails to be downloaded.

https://www.npmjs.com/package/pinkie-promise

Fails to install directly too:

```
$ npm install pinkie-promise
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for pinkie-promise
```

**Comment by ghost** [comment]
The same issue.

**Comment by nficca** [comment]
Looks like it's back up now.

**Comment by BlackHole1** [comment]
Temporary solution:
`npm install --save pinkie-promise@2.0.2`
@Eldelshell  @aprisniak @nficca

**Comment by Eldelshell** [comment]
@nficca yes, it's back... weird

**Comment by paulwib** [comment]
Erm yeah, but published by different NPM users. Was originally published by [floatdrop](https://webcache.googleusercontent.com/search?q=cache:q8F7GvBGRZAJ:https://www.npmjs.com/package/pinkie+&cd=1&hl=en&ct=clnk&gl=uk) now published by [puradox](https://www.npmjs.com/~puradox). [pinkie-promise](https://www.npmjs.com/package/pinkie-promise) has also been republished by [mbensch](https://www.npmjs.com/~mbensch).

Bit worrying if not published by the original author? Could be an attempt to hijack the packages?

**Comment by Jokero** [comment]
`pinkie-promise` is also not found now

**Comment by ghost** [comment]
https://github.com/npm/registry/issues/255

**Comment by Streamweaver** [comment]
Jan 23rd, not found still.  How is this still a problem?

**Comment by floatdrop** [comment]
@Streamweaver last actual version is `2.0.1` – check that you do not use local caching registry and right version.
