### ISSUE TITLE
Pinkie republished to NPM by user that isn't floatdrop

### ISSUE THREAD

**Issue by paulwib** [floatdrop/pinkie#18]
Pinkie disappeared briefly from npm, see #16, then reappeared again published by another user. Was originally published by [floatdrop](https://webcache.googleusercontent.com/search?q=cache:q8F7GvBGRZAJ:https://www.npmjs.com/package/pinkie+&cd=1&hl=en&ct=clnk&gl=uk) now published by [puradox](https://www.npmjs.com/~puradox). [pinkie-promise](https://www.npmjs.com/package/pinkie-promise) has also been republished by [mbensch](https://www.npmjs.com/~mbensch).

Bit worrying if not published by the original author. Could be an attempt to hijack the packages? Or just someone trying to help out? Would be good to get clarification from @floatdrop.

Original NPM page:

 ![Google cache screen shot of original NPM package](https://user-images.githubusercontent.com/29969/34643034-336ef878-f315-11e7-886c-69ba69d20bdd.png)

Current NPM page:

<img width="620" alt="screen shot 2018-01-06 at 19 12 55" src="https://user-images.githubusercontent.com/29969/34643070-b281f98a-f315-11e7-88de-c877bef4ab84.png">

**Comment by Jokero** [comment]
@floatdrop what's happened?

**Comment by paulwib** [comment]
Oh wow, all his packages have gone :boom:

Hope it's not another leftpad scenario.

**Comment by coffe4u** [comment]
Now the package isn't up at all. Failed deploys all over.

**Comment by Jokero** [comment]
https://github.com/npm/registry/issues/255

**Comment by coffe4u** [comment]
https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by stephnr** [comment]
It's getting worse. Looks like yarn is broken now. And yarn is used heavily by Heroku node projects!

**Comment by danielweck** [comment]
`pinkie` 2.0.5 has just been published by some other dev! (not original https://www.npmjs.com/~floatdrop )
https://www.npmjs.com/package/pinkie
https://www.npmjs.com/~puradox
@floatdrop this should be 2.0.4 right?

**Comment by danielweck** [comment]
`package-lock.json`:

```
     "pinkie": {
-      "version": "2.0.4",
-      "resolved": "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz",
-      "integrity": "sha1-clVrgM+g1IqXToDnckjoDtT3+HA=",
+      "version": "2.0.5",
+      "resolved": "https://registry.npmjs.org/pinkie/-/pinkie-2.0.5.tgz",
+      "integrity": "sha512-9fAxS/+I3fBLBLJpZkuUTa1nY78BDWiP4Z8NFebaBCt3NuInv31J4YrljAaktsJ5QodyQ1qyr5EdBzTITF1cxw==",
       "dev": true
     }
```

**Comment by danielweck** [comment]
Looks identical:
`2.0.4`:
https://unpkg.com/pinkie@2.0.4/index.js

`2.0.5`:
https://unpkg.com/pinkie@2.0.5/index.js

That's a massive potential security hole though! How can we trust / rely on the other dev  ( @puradox ) to maintain future `pinkie` updates?

**Comment by danielweck** [comment]
I posted at NPM's "registry" project too: https://github.com/npm/registry/issues/256

**Comment by danielweck** [comment]
@ceejbot statement from https://github.com/npm/registry/issues/255 :
> Beginning at 18:36 GMT today, 106 packages were made unavailable from the registry. 97 of them were restored immediately. Unfortunately, people published over 9 of them, causing delays in the restoration of those 9. We are continuing to clean up the overpublications. All installations that depend on the 106 packages should now be working.

I wonder if `pinkie` is one of the 9 identified packages?

**Comment by danielweck** [comment]
Follow-up:
https://github.com/npm/registry/issues/256#issuecomment-355785321
(probably a good idea to clear npm/yarn lockfiles, caches and node_modules)

**Comment by danielweck** [comment]
PS: this issue can now be closed.

**Comment by fischman** [comment]
NPM n00b here: is it not worrying that the "maintainers" field of several entries in https://registry.npmjs.org/pinkie/ still point to puradox?

**Comment by danielweck** [comment]
Very good point. NPM's internal "metadata" seems to have retained information about the unwanted package's publisher (as a "maintainer"), even though pinkie's public project metadata doesn't include "puradox" as a contributor.
https://unpkg.com/pinkie@2.0.4/package.json

Perhaps ask here: https://github.com/npm/registry/issues
...and please cross-reference the original issue: 
https://github.com/npm/registry/issues/256

**Comment by danielweck** [comment]
Interestingly, the package duplexer3 which was actually hijacked during the downtime (completely wiped and changed for a stupid console message) does not seem to have incorrect registry metadata (maintainers):
https://registry.npmjs.org/duplexer3

**Comment by danielweck** [comment]
Perhaps @puradox is a developer who worked with @floatdrop in the past? Can you please confirm?

**Comment by puradox** [comment]
Hey guys! Sorry for not posting sooner, I've been traveling quite a bit. Let me explained what happened:

I was in the middle of development when I noticed that the installation of one of my tools failed. I was receiving an error stating that `pinkie` was not to be found. So I visited https://www.npmjs.com/ to see for myself, and indeed, they were being reported as missing or non-existent. Thinking this was a possible `left-pad` incident, I sent a [tweet](https://twitter.com/purad0x/status/949723630077755393) over to @floatdrop, quickly forked `floatdrop/pinkie`, bumped the patch, and published it under my account. After that, it was working immediately and I was able to get back to work.

I had absolutely no intention of "hijacking" this package and apologize for any inconvenience this may have caused the maintainers of `pinkie` or the staff at npm.

Referencing [the latest npm blog post](http://blog.npmjs.org/post/169432444640/npm-operational-incident-6-jan-2018), it seems npm had an outage during the time I was attempting to install my tools. Knowing that this wasn't another `left-pad` incident is relieving, but other concerns come to mind regarding the security of npm.

**Comment by fischman** [comment]
@puradox thanks for chiming in!  
I hope npm/registry#258 can get the registry metadata restored to how it was before this excitement happened (plz follow up there if you know how to make it happen; I suspect the answer is it must be done by registry admins).

**Comment by danielweck** [comment]
Good to hear from you puradox :)
I responded at npm/registry, let's hope NPM comes up with further platform robustness / security improvements!
https://github.com/npm/registry/issues/256#issuecomment-356190370

**Comment by webmobiles** [comment]
just deleting yarn.lock and executing yarn install, solved. I m using yarn 1.9
