### ISSUE TITLE
Rejecting errors

### ISSUE THREAD

**Issue by dsblv** [floatdrop/pinkie#2]
I know I look like a guy who walks around poking everyone's face with something he just learned, and in fact I am, but... Isn't [this](https://github.com/floatdrop/pinkie/blob/master/index.js#L162-L168), [this](https://github.com/floatdrop/pinkie/blob/master/index.js#L207-L209) and [this](https://github.com/floatdrop/pinkie/blob/master/index.js#L242-L244) supposed to be rejections instead of thrown errors?

I mean, `Promise.reject()` is already implemented, so why not?

**Comment by floatdrop** [comment]
@dsblv [ES2015 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-executor) says:

```
    1. If NewTarget is undefined, throw a TypeError exception.
```

So, I guess, not.
