### ISSUE TITLE
A derivative

### ISSUE THREAD

**Issue by vitaly-t** [floatdrop/pinkie#4]
Thank you so much for this great little library!

I've been considering to start on my own version of a promise library, but never had enough time, but once I did, my brain was burning over proper `.then`-chaining.

After long experimenting I decided to look at the existing implementations instead, is when I found yours. And I decided to use your implementation as the basis for my own library. I hope you do not terribly mind.

What I wanted was to start with the basic implementation like this one, and then optimize the hell out of it, for maximum possible performance.

I started it as [nitrous](https://github.com/vitaly-t/nitrous), which at the moment is your code by at least 90%, but my goal is rewriting most of it.

I started by writing comprehensive tests on my side, to validate any possible change that I make.

Anyhow, thanks again for such a great example of the promise implementation, it saves me great deal of time and headache.

СПАСИБО!!! :+1:

**Comment by floatdrop** [comment]
Пожалуйста :)

**Comment by sindresorhus** [comment]
@vitaly-t Why not contribute to this library? This one has a lot of users and performance improvements would have a positive impact on a lot of projects.

**Comment by vitaly-t** [comment]
@sindresorhus the reasons are....

I initially wrote my own promise library, and though I didn't finish it, many of ideas I'd like to re-implement in this library.

At the moment my plan is:

Step-1: Adding comprehensive tests to cover every possible execution path;
Step-2: Adding comprehensive performance benchmarks
Step-3: Rewriting most of the original library as planned, while constantly looking at the tests and performance figures, to be sure in the positive impact of the changes.

In all, I am planning too much rewrite and too many changes to be doing it within this project, not just a few improvements. It wouldn't make sense to do it here. And I need complete autonomy doing it.
