### ISSUE TITLE
nested reject

### ISSUE THREAD

**Issue by vitaly-t** [floatdrop/pinkie#5]
Why in the following example:

``` javascript
promise.resolve(promise.resolve("nested"))
    .then(function (data) {
        console.log(data);
    });
```

we get the output of:

```
nested
```

while in this one:

``` javascript
promise.reject(promise.reject("nested"))
    .catch(function (error) {
        console.log(error);
    });
```

we get:

```
{ _then : undefined, _state : 3, _data : 'nested' }
```

Shouldn't the nested reject operation output `nested` the same as in the first example? I couldn't find any contradiction to this within the [promise spec](https://promisesaplus.com/).

**Comment by floatdrop** [comment]
Nope. See sections [25.4.4.4](https://people.mozilla.org/%7Ejorendorff/es6-draft.html#sec-promise.reject) and [25.4.4.5](https://people.mozilla.org/%7Ejorendorff/es6-draft.html#sec-promise.resolve).

**Comment by vitaly-t** [comment]
Thank you!
