### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by vitaly-t** [floatdrop/pinkie#6]
I've been doing some code coverage for your code, and was able to get 95% of it done, but the remaining 5% seem somewhat difficult to reproduce.

Here's the coverage report: https://coveralls.io/builds/4085399/source?filename=lib%2Findex.js

You can see in red lines where I couldn't get the coverage.

That report is however not that good. I've added instructions [here](https://github.com/vitaly-t/nitrous) for generating a local coverage report, which also includes execution path conditions, which is far more useful.

I appreciate if you can help me with the remaining coverage logic, i.e. tell me what kind of test needs to be executed for those cases.

This way we both can get better understanding of each execution path within the library, and be able to see if there is any redundancy in the code.

Thank you!

**Comment by floatdrop** [comment]
I don't quite have time for this, but added coverage report to track coverage improvements. See #8.

**Comment by vitaly-t** [comment]
@floatdrop I only asked you to advise on the kind of tests I'm missing, as I would write those myself.

You would benefit from it later when you do have time to do your own code coverage ;)
