### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by vitaly-t** [floatdrop/pinkie#7]
If we run `npm test`, or `npm run test`, we get the following error:

```
D:\Temp\test\node_modules\pinkie\node_modules\mocha\lib\utils.js:626
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'test'
    at Object.lookupFiles (D:\Temp\test\node_modules\pinkie\node_modules\mocha\lib\utils.js:626:15)
    at D:\Temp\test\node_modules\pinkie\node_modules\mocha\bin\_mocha:316:30
    at Array.forEach (native)
    at Object.<anonymous> (D:\Temp\test\node_modules\pinkie\node_modules\mocha\bin\_mocha:315:6)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
 npm ERR! Test failed.  See above for more details.
```

**Comment by floatdrop** [comment]
Nope, [working fine](https://travis-ci.org/floatdrop/pinkie/builds/90090008). Maybe Windows-related problem with mocha.

**Comment by vitaly-t** [comment]
Do you not support Windows?

By the way, I've been using the following tools for my tests:

``` javascript
 "devDependencies": {
    "istanbul": "0.4",
    "jasmine-node": "1.x"
  }
```

and they never gave me any platform-specific trouble ;)

**Comment by floatdrop** [comment]
@vitaly-t I don't have neither PC or virtual environment with Windows, so I don't test under this platform (unless module is platform fragile).

**Comment by vitaly-t** [comment]
Thanks! I will try it on a Mac OS to see if it works there at least, and update here.

P.S. I really appreciate if you come back to me on that Code Coverage question, as I'm stuck there :)

**Comment by vitaly-t** [comment]
@floatdrop I have tried running tests on the latest OS X, and got the exact same error as on Windows. So it is not OS-related issue.

Have you even tried to install it locally and run the tests since I reported the issue?

**Comment by floatdrop** [comment]
@vitaly-t yes.
